<?php
/**
 * @var \Dnd\OffersBanner\Block\Category\Offers $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<div class="swiper-container offers-banner-slider">
    <div class="swiper-wrapper">
        <?php foreach ($block->getOffersBannerList() as $offer): ?>
            <div class="swiper-slide">
                <a href="<?= $escaper->escapeUrl($offer['link']) ?>">
                    <img src="<?= $escaper->escapeUrl($offer['image']) ?>"
                         alt="<?= $escaper->escapeHtml($offer['label']) ?>" />
                </a>
            </div>
        <?php endforeach; ?>
    </div>
    <div class="swiper-pagination"></div>
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
</div>
